import Cells from "../cells";

function exportLaTeX(title: string, description: string, cells: Cells): string {
    const lines = [];

    lines.push(String.raw`% generated by quarrel ${new Date()}`);
    lines.push(String.raw`% requires the 'crossword' package from CTAN`);
    lines.push(String.raw`\documentclass{article}`);
    lines.push(String.raw`\usepackage{cwpuzzle}`);
    lines.push(String.raw`\begin{document}`);
    lines.push(String.raw`\title{${title}}`);
    lines.push(String.raw`\date{}`);
    lines.push(String.raw`\author{${description}}`);
    lines.push(String.raw`\maketitle`);
    lines.push(String.raw`\begin{Puzzle}{${cells.size()}}{${cells.size()}}`);
    for (const row of cells.cells) {
        let line = "";
        for (const cell of row) {
            line += "|";
            if (cell.value === "") {
                line += "*";
            } else {
                if (cell.clueNum() !== null) line += `[${cell.clueNum()}]`;
                line += cell.value;
            }
        }
        line += "|.";
        lines.push(line);
    }
    lines.push(String.raw`\end{Puzzle}`);

    lines.push(String.raw`\begin{PuzzleClues}{\textbf{Across}}`);
    for (const [cell, _] of cells.allCells()) {
        const { acrossClue: clue } = cell;
        if (clue !== null) {
            lines.push(
                String.raw`\Clue{${clue.num}}{${clue.answer}}{${clue.clue}}`,
            );
        }
    }
    lines.push(String.raw`\end{PuzzleClues}`);

    lines.push(String.raw`\begin{PuzzleClues}{\textbf{Down}}`);
    for (const [cell, _] of cells.allCells()) {
        const { downClue: clue } = cell;
        if (clue !== null) {
            lines.push(
                String.raw`\Clue{${clue.num}}{${clue.answer}}{${clue.clue}}`,
            );
        }
    }
    lines.push(String.raw`\end{PuzzleClues}`);

    lines.push(String.raw`\end{document}`);

    return lines.join("\n");
}

export default exportLaTeX;
